<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationHighDpiMode>SystemAware</ApplicationHighDpiMode>
    <ApplicationIcon>app.ico</ApplicationIcon>
    <AssemblyTitle>云曦PC统计</AssemblyTitle>
    <Product>云曦PC统计</Product>
    <Version>1.4.5</Version>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
    <SatelliteResourceLanguages>zh-Hans</SatelliteResourceLanguages>
    <AssemblyName>YunXiStatistician</AssemblyName>
    <RootNamespace>PcCompanionMonitor</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\InstallerSource\CloudXiInstaller.csproj" />
  </ItemGroup>
</Project>
