<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyTitle>云曦PC统计 安装支持</AssemblyTitle>
    <Product>云曦PC统计</Product>
    <Version>1.4.5</Version>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
    <SatelliteResourceLanguages>zh-Hans</SatelliteResourceLanguages>
    <AssemblyName>CloudXiInstaller</AssemblyName>
    <RootNamespace>CloudXiPcMonitor.Installer</RootNamespace>
  </PropertyGroup>

</Project>
